config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'

  # SignIn/SignUp/SignOut
  get '/sign-up' => 'registrations#new', as: :signup
  post '/sign-up' => 'registrations#create'
  get '/sign-in' => 'authentication#new', as: :signin
  post '/sign-in' => 'authentication#create'
  get '/sign-out' => 'authentication#destroy', as: :signout

  resources :conversations do
    resources :messages
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :sender,    foreign_key: :sender_id,    class_name: 'User'
  belongs_to :recipient, foreign_key: :recipient_id, class_name: 'User'
  has_many   :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, :scope => :recipient_id

  scope :between, -> (sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
  end

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id

  def message_time
    created_at.strftime("%m/%d/%y at %l:%M %p")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :first_name, :email,  presence: true
  validates :email, uniqueness: true
  validates :password, length: { minimum: 4 }
  validates :first_name, length: { minimum: 2 }

  has_secure_password

  has_many :conversations, foreign_key: :sender_id

  def full_name
    first_name + ' ' + last_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protect_from_forgery with: :null_sessions

  def current_user
    User.find_by(id: session[:user_id])
  end

  def authenticate_user
    if !current_user
      redirect_to signin_path, notice: "You must be signed in to do that!"
    end
  end

  helper_method :current_user, :authenticate_user
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:alert] = "Username/password combination is invalid"
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user

  def index
    @users = User.all
    @conversations = Conversation.all
  end

  def create
    if Conversation.between(params[:sender_id],params[:recipient_id]).present?
      @conversation = Conversation.between(params[:sender_id], params[:recipient_id]).first
    else
      @conversation = Conversation.create!(conversation_params)
    end
    redirect_to conversation_messages_path(@conversation)
  end

private
  def conversation_params
    params.permit(:sender_id, :recipient_id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action do
    @conversation = Conversation.find(params[:conversation_id])
  end

  def index
    @users = User.all
    @messages = @conversation.messages
    if @messages.length > 10
      @over_ten = true
      @messages = @messages[-10..-1]
    end
    if params[:m]
      @over_ten = false
      @messages = @conversation.messages
    end
    if @messages.last
      if @messages.last.user_id != current_user.id
        @messages.last.read = true
      end
    end

    @message = @conversation.messages.new
  end

  def new
    @message = @conversation.messages.new
  end

  def create
    message = @conversation.messages.new(message_params)
    if message.save
      ActionCable.server.broadcast 'messages',
                                   user_id: message.user.id,
                                   user:    message.user.full_name,
                                   time:    message.message_time,
                                   body:    message.body,
                                   room:    @conversation.id
      head :ok
    else
      redirect_to conversation_messages_path(@conversation)
    end
  end

  private
  def message_params
    params.require(:message).permit(:body, :user_id)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "You're Signed Ip!"
      redirect_to root_path
    else
      render :new
      flash[:alert] = "Your registration could not be completed"
    end
  end

  private
  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :email,
      :password,
      :password_confirmation
    )
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authentication/new.html.erb
<h1>Sign In</h1>
<div class="ui form segment">
  <%= form_tag signin_path html: {class: "ui form segment"} do |f| %>

  <div class="two fields">
    <div class="field">
      <%= label_tag :email %>
      <div class="field">
        <%= email_field_tag :email %>
      </div>
    </div>

    <div class="field">
      <%= label_tag :password %>
      <div class="field">
        <%= password_field_tag :password %>
      </div>
    </div>
    <div class="field">
      <%= submit_tag "Sign In", class: "ui submit button" %>
    </div>
  </div>
  <% end %>

</div>

app/views/layouts/_users_panel.html.erb
<% if current_user %>
    <div class="large screen only five wide column">
      <div class="ui segment">
        <h3>All Users</h3>
        <div class="ui list">
          <% @users.each do |user| %>
              <% if current_user && user.id != current_user.id %>
                  <div class="item" user_id="<%= user.id %>">
                    <%= link_to user.full_name, conversations_path(sender_id: current_user.id, recipient_id: user.id),
                                method: 'post' %>
                    <div class="ui label">
                      <i class="mail icon"></i>
                      <span class="counter"></span>
                    </div>
                    <!--Popup messages-->
                    <div class="message_popup ui left pointing blue basic label" style="display:none"></div>
                  </div>

              <% end %>
          <% end %>
        </div>
      </div>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SimpleMessagesApp</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
</head>
<body>
<!--Navigation-->
<div class="ui grid">
  <div class="row">
    <div class="fourteen wide centered column">
      <h2 class="ui header">
        <i class="mail icon"></i>
        <div class="content">
          Messenger
        </div>
      </h2>
      <div class="ui blue inverted menu">
        <i class="home icon"></i><%= link_to "Home", root_path, class: "item" %>
        <% if current_user %>
            <div class="right menu">
              <%= link_to current_user.full_name, '#', class: "item" %>
              <%= link_to 'Sign Out', signout_path, class: "item" %>
            </div>
        <% else %>
            <div class="right menu">
              <%= link_to 'Sign Up', signup_path, class: "item" %>
              <%= link_to "Sign-In", signin_path, class: "item" %>
            </div>
        <% end %>
      </div>
      <!--End Navigation-->
      <!--Main-->
      <div class="ui two column stackable grid container">
        <div class="large screen only eleven wide column">
          <%= yield %>
        </div>
        <%= render 'layouts/users_panel' %>
      </div>
      <!--End Main-->
    </div>
  </div>
</div>
</body>
</html>

app/views/messages/index.html.erb
<% if @over_ten %>
   <%= link_to 'Show Previous', '?m=all' %>
<% end %>

<div id="chat_room_<%= @conversation.id %>" class="ui segment">
  <% @messages.each do |message| %>
    <% if message.body %>
      <% user = User.find(message.user_id) %>
      <div class="item">
        <div class="content">
          <div class="header"><strong><%= user.full_name %></strong> <%= message.message_time %></div>
          <div class="list">
            <div class="item">
              <i class="right triangle icon"></i>
              <%= message.body %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<%= form_for [@conversation, @message], remote: true, authenticity_token: true, html: {class: "ui reply form"} do |f| %>
    <a class="ui grey ribbon label">
      <% if current_user.id == @conversation.recipient_id %>
          <% recipient_id = @conversation.sender_id %>
      <% else %>
          <% recipient_id = @conversation.recipient_id %>
      <% end %>
      Message to: <%= User.find(recipient_id).full_name%>
    </a>
    <div class="field">
    <%= f.text_area :body, class: "form-control" %>
  </div>
    <%= f.text_field :user_id, value: current_user.id, type: "hidden"  %>
  <div>
    <%= f.submit "Add Reply", class: "ui blue labeled submit icon button" %>
  </div>

<% end %>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class= "alert alert-danger col-md-offset-2">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this <%= "#{(object.class).to_s.downcase}" %> from being saved:</h2>
    <ul>
      <% object.errors.full_messages.each do |message| %>
      <li><%= message %> </li>
      <% end %>
    </ul>
  </div>
<% end %>